version: "3.8"
service:
  app:
    build: .
    environment:
      DATABASE_URL: postgresql://enock:87654321@db:5432/county
    env_file: .env
    depends_on:
      - db
    ports:
      - "5000:5000"
  db:
    image: postgresql:15-alpine  
    environment:
      POSTGRES_USER: enock
      POSTGRES_PASSWORD: 87654321
      POSTGRES_DB: county
    volumes:
    postgres_data: /var/lib/postgresql/data
volumes:
  postgres_data