services:
  app:
    build: .
    environment:
      DATABASE_URL: postgres://roparon:roparon@db:5432/county
    env_file: .env
    depends_on:
      - db
    ports:
      - "5000:5000"
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: roparon
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: county
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: